POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhpaGkiLCJpZCI6IjVmNzg2OTBlZGI3NmQyMzljYmIwNzMzOSIsImlhdCI6MTYwMjU3NTg1N30.xM2wAQWHkelJizmZAtM4sBIpi6UG0K7558rne1Zkbmc

{
  "title": "dirliiiii",
  "author": "kebu",
  "url": "urli",
  "likes": 2
}